services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        depends_on:
            - redis
        volumes:
            - ./:/var/www
        container_name: test_mayflower_app
        ports:
            - "8000:8000"
        command: php artisan octane:start --host=0.0.0.0 --port=8000

    redis:
        image: redis:7-alpine
        container_name: test_mayflower_country-visits-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        volumes:
            - ./_docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
